import { VIEWS } from "@/components/3D/CameraRig";

const DEFAULT_VIEW_POSITION = VIEWS[0].position;
const DEFAULT_ANCHOR_ANGLE =
  Math.atan2(DEFAULT_VIEW_POSITION[2], DEFAULT_VIEW_POSITION[1]) - 0.2;
const DEFAULT_ANCHOR_RADIUS =
  Math.hypot(DEFAULT_VIEW_POSITION[1], DEFAULT_VIEW_POSITION[2]) + 0.1;

export const DEFAULT_UNIVERSE_X_OFFSET = -0.2;
export const DEFAULT_UNIVERSE_ANCHOR_Y =
  Math.cos(DEFAULT_ANCHOR_ANGLE) * DEFAULT_ANCHOR_RADIUS;
export const DEFAULT_UNIVERSE_ANCHOR_Z =
  Math.sin(DEFAULT_ANCHOR_ANGLE) * DEFAULT_ANCHOR_RADIUS;
